name: glow_blocks_engine
description: Blocks engine for visual programming in Glow
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  glow_core:
    path: ../glow_core

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
