name: {{package_name}}
description: {{description}}
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
{{#is_flutter}}
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
{{/is_flutter}}{{^is_flutter}}
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
{{/is_flutter}}