name: glow_app
description: Glow - Social Operating System
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Glow packages
  glow_core:
    path: ../../packages/glow_core
  glow_domain:
    path: ../../packages/glow_domain
  glow_data:
    path: ../../packages/glow_data
  glow_api:
    path: ../../packages/glow_api
  glow_auth:
    path: ../../packages/glow_auth
  glow_realtime:
    path: ../../packages/glow_realtime
  glow_blocks_engine:
    path: ../../packages/glow_blocks_engine
  glow_blocks_flutter:
    path: ../../packages/glow_blocks_flutter
  glow_observability:
    path: ../../packages/glow_observability
  glow_ui:
    path: ../../packages/glow_ui
  
  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # DI
  get_it: ^7.7.0
  injectable: ^2.4.4
  
  # Navigation
  go_router: ^14.3.0
  
  # Storage
  shared_preferences: ^2.3.3
  
  # Backend
  supabase_flutter: ^2.9.1
  
  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  
  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.7
  rxdart: ^0.28.0
  
  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Media
  image_picker: ^1.1.2
  
  # Analytics
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  
  # Testing
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/shaders/
  
  fonts:
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-Regular.ttf
        - asset: assets/fonts/InterDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterDisplay-Bold.ttf
          weight: 700
  
  generate: true
