name: glow_data
description: Data layer - repositories, datasources and models for Glow
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  glow_core:
    path: ../glow_core
  glow_domain:
    path: ../glow_domain

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
